version: "3.3"

services:
  jumpserver:
    container_name: jumpserver
    image: cyberxsecurity/dvwa
    volumes:  
      - /home/azureuser/test_dir:/test_dir
    networks:
      app-net:
        ipv4_address: 10.10.0.3

  ansible:
    container_name: ansible
    image: cyberxsecurity/ansible
    tty: true
    volumes:  
      - /home/azureuser/test_dir:/test_dir
      - /home/azureuser/etc_ansible:/etc/ansible
      - /home/azureuser/.ssh:/root/.ssh
    networks:
      app-net:
        ipv4_address: 10.10.0.4


networks:
  app-net:
    ipam:
      driver: default
      config:
        - subnet: "10.10.0.0/24"    
