  ansible:
    container_name: ansible
    image: cyberxsecurity/ansible
    tty: true
    volumes:  
      - /home/azureuser/test_dir:/test_dir
      - /home/azureuser/etc_ansible:/etc/ansible
      - /home/azureuser/.ssh:/root/.ssh
    #networks:
    #  app-net:
    #    ipv4_address: 10.10.0.4
